version: '3'

services:
  api_movies:
    container_name: api_movies
    build: ./backend
    restart: always
    volumes: 
      - ./backend/src:/backend/src
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://mongodb:27017/CreathusMovies
    networks:
      - api-movies-network

  mongodb:
    container_name: api_movies_db
    image: mongo:5.0.7
    restart: always
    ports:
      - 27017:27017
    networks:
      - api-movies-network

networks:
  api-movies-network: