version: '3'

services:
  app:
    container_name: app_movies
    build: ./frontend
    restart: always
    volumes: 
      - ./frontend/src:/frontend/src
    # depends_on:
    #   - api_movies
    ports:
      - 5173:5173
    environment:
      - REACT_APP_BACKEND_PORT=3001
      - REACT_APP_BACKEND_HOST=api-movies 
    networks:
      - api-movies-network

  # api_movies:
  #   container_name: api_movies
  #   build: ./backend
  #   restart: always
  #   volumes: 
  #     - ./backend/src:/backend/src
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - MONGO_URI=mongodb://mongodb:27017/CreathusMovies
  #   networks:
  #     - api-movies-network

  # mongodb:
  #   container_name: api_movies_db
  #   image: mongo:5.0.7
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - api-movies-network

networks:
  api-movies-network:
    driver: bridge